### ISSUE TITLE
Is ami-species working in the VM?

### ISSUE THREAD

**Issue by rossmounce** [ContentMine/ebi_workshop_20141006#17]
I  point it at the PLOS ONE full-text XML file provided and give it an output directory but that isn't working for me. Did I get something wrong syntax-wise?

```bash
workshop@contentmine:~$ ami-species -i /usr/share/xhtml2stm-repo/exampleData/species/journal.pone.0077058.xml -o /home/workshop/target/
0    [main] DEBUG org.xmlcml.xhtml2stm.visitor.ArgProcessor  - writing to output): /home/workshop/target/
4    [main] ERROR org.xmlcml.xhtml2stm.visitable.xml.XMLVisitable  - Cannot parse document: /usr/share/xhtml2stm-repo/exampleData/species/journal.pone.0077058.xml (java.lang.NoClassDefFoundError: org/codehaus/plexus/util/FileUtils) 
4    [main] DEBUG org.xmlcml.xhtml2stm.visitable.AbstractVisitable  - in: visitableList: [org.xmlcml.xhtml2stm.visitable.xml.XMLVisitable@cf3539]
inputArg: /usr/share/xhtml2stm-repo/exampleData/species/journal.pone.0077058.xml
extension: xml
extensions: [Ljava.lang.String;@1af4309
isDirectory: false
recursive: false

4    [main] DEBUG org.xmlcml.xhtml2stm.visitable.AbstractVisitable  - out: /home/workshop/target
4    [main] DEBUG org.xmlcml.xhtml2stm.visitor.VisitorOutput  - outputFile: /home/workshop/target
4    [main] DEBUG org.xmlcml.xhtml2stm.visitor.VisitorOutput  - output /home/workshop/target
5    [main] DEBUG org.xmlcml.xhtml2stm.visitor.VisitorOutput  - mkdirs
5    [main] DEBUG org.xmlcml.xhtml2stm.visitor.VisitorOutput  - basename journal.pone.0077058
5    [main] DEBUG org.xmlcml.xhtml2stm.visitable.AbstractVisitable  - writing: /home/workshop/journal.pone.0077058.xml
5    [main] DEBUG org.xmlcml.xhtml2stm.visitable.AbstractVisitable  - InputVisitables 1
5    [main] DEBUG org.xmlcml.xhtml2stm.visitable.AbstractVisitable  - outfileList [/usr/share/xhtml2stm-repo/exampleData/species/journal.pone.0077058.xml]
Exception in thread "main" java.lang.NoClassDefFoundError: org/codehaus/plexus/util/FileUtils
	at org.xmlcml.xhtml2stm.visitable.xml.XMLVisitable.createContainersFromFiles(XMLVisitable.java:77)
	at org.xmlcml.xhtml2stm.visitable.xml.XMLVisitable.getXMLContainerList(XMLVisitable.java:66)
	at org.xmlcml.xhtml2stm.visitor.species.SpeciesVisitor.visit(SpeciesVisitor.java:54)
	at org.xmlcml.xhtml2stm.visitor.AbstractVisitor.visitSubclassed(AbstractVisitor.java:218)
	at org.xmlcml.xhtml2stm.visitor.AbstractVisitor.visit(AbstractVisitor.java:50)
	at org.xmlcml.xhtml2stm.visitor.AbstractVisitor.runArgProcessor(AbstractVisitor.java:143)
	at org.xmlcml.xhtml2stm.visitor.AbstractVisitor.visitArgs(AbstractVisitor.java:108)
	at org.xmlcml.xhtml2stm.visitor.AbstractVisitor.processArgs(AbstractVisitor.java:398)
	at org.xmlcml.xhtml2stm.visitor.species.SpeciesVisitor.main(SpeciesVisitor.java:164)
```

**Comment by jcmolloy** [comment]
Old issue - closing
